# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-08 22:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Auction',
            new_name='Users',
        ),
    ]
