# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-08 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20180608_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auctions',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('owner_id', models.IntegerField()),
                ('item', models.CharField(max_length=50)),
                ('starting_bid', models.IntegerField()),
                ('starting_time', models.DateTimeField(auto_now_add=True)),
                ('ending_time', models.DateTimeField()),
                ('highest_bid', models.FloatField()),
                ('winner_id', models.IntegerField()),
            ],
        ),
    ]
