# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-09 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctions',
            name='image',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
