# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-10 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auctions_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='highest_bid',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='owner_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='auctions',
            name='winner_id',
            field=models.IntegerField(null=True),
        ),
    ]
