# Generated by Django 4.1.1 on 2022-11-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20180610_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctions',
            name='highest_bid',
            field=models.FloatField(default=0, null=True),
        ),
    ]
